include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/build/**"
    - "**/test/**"
    - "**/coverage/**"
    - "**/lib/generated_plugin_registrant.dart"

  errors:
    # Treat specific lints as errors
    invalid_use_of_visible_for_testing_member: error
    use_build_context_synchronously: error
    deprecated_member_use_from_same_package: error
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    unnecessary_const: error
    unnecessary_new: error
    unnecessary_this: error
    unused_element: error
    unused_field: error
    unused_import: error
    unused_local_variable: error

linter:
  rules:
    # Best Practices
    - always_declare_return_types
    - always_use_package_imports
    - avoid_empty_else
    - avoid_print
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - dangling_library_doc_comments
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - null_check_on_nullable_type_parameter
    - omit_local_variable_types
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - unsafe_html
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
    - valid_regexps

    # Flutter Specific
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_super_parameters
    - use_test_throws_matchers

    # Performance
    - avoid_function_literals_in_foreach_calls
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_returning_this
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_foreach

    # Style
    - camel_case_extensions
    - constant_identifier_names
    - directives_ordering
    - lines_longer_than_80_chars
    - non_constant_identifier_names
    - prefer_expression_function_bodies
    - prefer_final_locals
    - prefer_single_quotes
    - sort_pub_dependencies
    - unnecessary_brace_in_string_interps
    - unnecessary_lambdas
    - unnecessary_string_escapes
    - unnecessary_string_interpolations

    # Documentation
    - comment_references
    - package_api_docs
    - slash_for_doc_comments
