name: mycard
description: "Application de création de cartes de visite numériques avec templates et événements"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase Auth
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  
  # File sharing
  file_picker: ^8.1.2
  
  # State management
  flutter_riverpod: ^2.4.9
  
  # UI
  flutter_svg: ^2.0.9
  
  # Routing
  go_router: ^12.1.3
  
  # UI
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  http: any
  
  # Image handling
  image: ^4.1.7
  image_picker: ^1.0.4
  
  # Localization
  intl: ^0.20.2
  
  # Utilities
  json_annotation: ^4.8.1
  
  # Utilities
  path: any
  path_provider: ^2.1.1
  
  # Image handling
  pdf: ^3.10.4
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Image handling
  screenshot: ^3.0.0
  
  # File sharing
  share_plus: ^7.2.2
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Utilities
  uuid: any
  
  # Utilities
  web_socket_channel: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.7
  
  # Linting
  flutter_lints: ^5.0.0
  
  # Code generation
  hive_generator: ^2.0.1
  
  # Code generation
  json_serializable: ^6.7.1
  
  # Testing
  mocktail: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/events/
    - assets/templates/
    - assets/data/

